# Generated by Django 2.2.4 on 2019-08-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=30, null=True),
        ),
    ]
