# Generated by Django 2.2.4 on 2019-08-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones_app', '0002_auto_20190826_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=30),
        ),
    ]
