# Generated by Django 2.2.4 on 2019-08-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones_app', '0006_auto_20190827_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='phones_app.CartItem'),
        ),
    ]
