# Generated by Django 2.2.4 on 2019-08-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones_app', '0008_cartitem_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='phone', upload_to='site_images'),
        ),
    ]
