# Generated by Django 2.2.4 on 2019-08-29 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phones_app', '0009_auto_20190828_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('last_name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('buying_type', models.CharField(choices=[('Picking up', 'Picking up'), ('At home', 'At home')], max_length=12)),
                ('comment', models.TextField(max_length=200)),
                ('items', models.ManyToManyField(to='phones_app.Cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
