# Generated by Django 2.2.4 on 2019-08-29 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones_app', '0010_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='users_cart',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='phones_app.Cart'),
            preserve_default=False,
        ),
    ]
