# Generated by Django 2.2.4 on 2019-08-29 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones_app', '0011_auto_20190829_1201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
