# Generated by Django 2.2.4 on 2019-08-29 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones_app', '0015_shopuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='orders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='phones_app.Order'),
        ),
    ]
