# Generated by Django 2.2.4 on 2019-08-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones_app', '0016_auto_20190829_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
