# Generated by Django 2.2.4 on 2019-08-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones_app', '0017_auto_20190830_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Payed', 'Payed'), ('Not payed', 'Not Payed')], default='Not Payed', max_length=12),
        ),
    ]
