# Generated by Django 2.2.4 on 2019-08-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones_app', '0018_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Payed', 'Payed'), ('Not Payed', 'Not Payed')], default='Not Payed', max_length=12),
        ),
    ]
